# - https://docs.docker.com/build/ci/github-actions/push-multi-registries/

# - https://github.com/docker/build-push-action

name: "æ‰“åŒ…æŽ¨é€ Docker é•œåƒ"
description: "æ‰“åŒ… Docker é•œåƒå¹¶æŽ¨é€åˆ° Docker Hub"
inputs:
  file:
    description: "Dockerfile æ–‡ä»¶è·¯å¾„"
    default: "./Dockerfile"
    required: false
  context:
    description: "Docker æž„å»ºä¸Šä¸‹æ–‡è·¯å¾„"
    default: "."
    required: false
  platforms:
    description: "Docker æž„å»ºå¹³å°"
    default: "linux/amd64,linux/arm64"
    required: false
  push:
    description: "æ˜¯å¦æŽ¨é€ Docker é•œåƒ"
    default: "false"
    required: false
  load:
    description: "æ˜¯å¦åŠ è½½ Docker é•œåƒ"
    default: "false"
    required: false
  meta_images:
    description: "docker/metadata-action çš„ images å‚æ•°"
    required: false
  meta_tags:
    description: "docker/metadata-action çš„ tags å‚æ•°"
    required: false
  cache-from:
    description: "docker/build-push-action çš„ cache-from å‚æ•°"
    required: false
  cache-to:
    description: "docker/build-push-action çš„ cache-to å‚æ•°"
    required: false
  build-args:
    description: "Docker æž„å»ºå‚æ•°ï¼Œæ ¼å¼å¦‚: KEY1=VALUE1,KEY2=VALUE2"
    required: false
outputs:
  imageid:
    description: "Docker é•œåƒ ID"
    value: ${{ steps.build.outputs.imageid }}
runs:
  using: "composite"
  steps:
    - name: echo Start
      shell: bash
      run: echo -e "\n[$(date +'%Y-%m-%d %H:%M:%S')] ðŸ¤–ðŸ¤–ðŸ¤– Start ðŸ¤–ðŸ¤–ðŸ¤–"

    - id: check-git-folder
      if: ${{ env.CALLED_DOCKER_BUILD_PUSH != 'true' }}
      shell: bash
      run: |
        #     ðŸ¤– åˆ¤æ–­æ˜¯å¦å­˜åœ¨ .git æ–‡ä»¶å¤¹ ðŸ¤–
        [ -d .git ] && { echo "ðŸ¤– Found .git folder"; echo "git-folder-exists=true" >> $GITHUB_OUTPUT; } || { echo "ðŸ¤– No .git folder found"; echo "git-folder-exists=false" >> $GITHUB_OUTPUT; }
    - uses: actions/checkout@main
      if: steps.check-git-folder.outputs.git-folder-exists == 'false' && env.CALLED_DOCKER_BUILD_PUSH != 'true'
      with:
        filter: blob:none
        show-progress: false

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        context: git
        # flavor
        images: ${{ inputs.meta_images }}
        tags: ${{ inputs.meta_tags }}
        # sep-tags: ','
        # sep-labels: ','

    - name: Set up QEMU
      if: ${{ env.CALLED_DOCKER_BUILD_PUSH != 'true' }}
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: ${{ env.CALLED_DOCKER_BUILD_PUSH != 'true' }}
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}
        build-args: ${{ inputs.build-args }}

    - name: echo End
      shell: bash
      run: |
        echo -e "\n[$(date +'%Y-%m-%d %H:%M:%S')] ðŸ¤–ðŸ¤–ðŸ¤– End ðŸ¤–ðŸ¤–ðŸ¤–"
        echo "CALLED_DOCKER_BUILD_PUSH=true" >> $GITHUB_ENV