# ðŸ”— Links:
# Source file: https://github.com/obytes/react-native-template-obytes/blob/master/.github/actions/setup-node-pnpm-install/action.yml
# Composite actions docs: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

# âœï¸ Description:
# This is a composite action, which means it can be used in other actions.
# It is used in almost all workflows to set up the environment and install dependencies.
# Updating  the package manager or Node version here will be reflected in all workflows.

# ðŸ‘€ Example usage:
#       - name : ðŸ“¦ Setup Node + PNPM + install deps
#         uses: ./.github/actions/setup-node-pnpm-install

name: "Setup Node Environment"
description: "Setup pnpm + Node.js + install dependencies"
runs:
  using: "composite"
  steps:
    - id: check-git-folder
      shell: bash
      run: |
        # ðŸ¤–----åˆ¤æ–­æ˜¯å¦å­˜åœ¨ .git æ–‡ä»¶å¤¹----ðŸ¤– #
        [ -d .git ] && { echo "ðŸ¤– Found .git folder"; echo "git-folder-exists=true" >> $GITHUB_OUTPUT; } || { echo "ðŸ¤– No .git folder found"; echo "git-folder-exists=false" >> $GITHUB_OUTPUT; }

    - uses: actions/checkout@v4.2.1
      if: steps.check-git-folder.outputs.git-folder-exists == 'false'
      with:
        # fetch-depth: 0 # zero stands for full checkout, which is required for semantic-release
        filter: blob:none # we don't need all blobs, only the full tree
        show-progress: false

    - shell: bash
      id: prepare
      run: |
        # ðŸ¤–----å‡†å¤‡æ•°æ®----ðŸ¤– #

        # åŒ…ç®¡ç†å™¨
        packageManager=$(node -p "try { require('./package.json').packageManager; } catch(e) { '' }")
        echo "ðŸ¤– åŒ…ç®¡ç†å™¨(package.json): $packageManager"
        echo "packageManager=$packageManager" >> $GITHUB_OUTPUT

        # è®¾ç½®pnpmç‰ˆæœ¬
        pnpmVersion=""
        if [ -z "$packageManager" ] || [ "$packageManager" == "undefined" ]; then
          pnpmVersion="latest"
        fi
        echo "pnpmVersion=$pnpmVersion" >> $GITHUB_OUTPUT

        # pnpmæ˜¯å¦å·²å®‰è£…
        pnpmInstalled=$(which pnpm > /dev/null && echo "true" || echo "false")
        echo "ðŸ¤– å·²å®‰è£…pnpm: $pnpmInstalled $( [ "$pnpmInstalled" == "true" ] && echo ". version: $(pnpm --version)" )"
        echo "pnpmInstalled=$pnpmInstalled" >> $GITHUB_OUTPUT

        # åˆ¤æ–­ pnpm-lock.yaml æ–‡ä»¶æ˜¯å¦å­˜åœ¨
        pnpm_lock_exists="false"
        [ -f pnpm-lock.yaml ] && pnpm_lock_exists="true"
        echo "ðŸ¤– æœ‰pnpm-lock.yaml: $pnpm_lock_exists"
        echo "pnpm-lock-exists=$pnpm_lock_exists" >> $GITHUB_OUTPUT

        # Nodeç‰ˆæœ¬
        touch .npmrc # å¦‚æžœä¸å­˜åœ¨åˆ™åˆ›å»º .npmrc æ–‡ä»¶
        nodeInNpmrc=$(sed -n 's/.*use-node-version=\([0-9.]*\).*/\1/p' .npmrc)
        nodeInNpmrcMajor=$(echo $nodeInNpmrc | cut -d. -f1)
        echo "ðŸ¤– Nodeç‰ˆæœ¬(.npmrc): $nodeInNpmrc -> $nodeInNpmrcMajor"
        nodeVersion=${nodeInNpmrcMajor:-"lts/*"} # å¦‚æžœæœªå®šä¹‰åˆ™ä½¿ç”¨é»˜è®¤å€¼
        echo "nodeVersion=$nodeVersion" >> $GITHUB_OUTPUT

        sed -i '/use-node-version/d' .npmrc;
        sed -i '/node-mirror/d' .npmrc;

    - uses: pnpm/action-setup@v4 # https://github.com/pnpm/action-setup?tab=readme-ov-file#inputs
      if: steps.prepare.outputs.pnpmInstalled == 'false'
      with:
        version: ${{ steps.prepare.outputs.pnpmVersion }}

    - uses: actions/setup-node@v4 # https://github.com/actions/setup-node?tab=readme-ov-file#usage
      with:
        node-version: ${{ steps.prepare.outputs.nodeVersion }}
        cache: ${{ steps.prepare.outputs.pnpm-lock-exists == 'true' && 'pnpm' || '' }}

    - run: pnpm install --frozen-lockfile
      if: steps.prepare.outputs.pnpm-lock-exists == 'true'
      shell: bash
