on:
  pull_request:
    paths:
      - "setup-node-environment/**"
      - ".github/workflows/setup-node-environment.yml"
  push:
    paths:
      - "setup-node-environment/**"
      - ".github/workflows/setup-node-environment.yml"
env:
  TZ: Asia/Shanghai

jobs:
  using-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yanhao98/composite-actions/setup-node-environment@main
  no-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-environment@main