on:
  push:
    branches:
      - main
    paths:
      - "setup-node-environment/**"
      - ".github/workflows/setup-node-environment.yml"
env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: before
        run: |
          set -x
          which pnpm || true
          node -v

      - uses: yanhao98/composite-actions/setup-node-environment@main

      - name: Check Node and PNPM versions
        run: |
          set -x
          which pnpm
          node -v
          pnpm node -v
