on:
  pull_request:
    paths:
      - "setup-node-environment/**"
      - ".github/workflows/setup-node-environment.yaml"
  push:
    paths:
      - "setup-node-environment/**"
      - ".github/workflows/setup-node-environment.yaml"
env:
  TZ: Asia/Shanghai

jobs:
  using-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: yanhao98/composite-actions/setup-node-environment@main
  no-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-environment@main
  using-pnpm-container:
    runs-on: ubuntu-latest
    container: yanhao98/runner-images:pnpm
    steps:
      - uses: yanhao98/composite-actions/setup-node-environment@main
  no_npmrc_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: rm -f .npmrc
      - uses: yanhao98/composite-actions/setup-node-environment@main
  with-package-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Add packageManager to package.json
        run: |
          node -e "const pkg = require('./package.json'); pkg.packageManager = 'pnpm@9.12.2'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2))"
      - uses: yanhao98/composite-actions/setup-node-environment@main
  without-package-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Remove packageManager from package.json
        run: |
          node -e "const pkg = require('./package.json'); delete pkg.packageManager; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2))"
      - uses: yanhao98/composite-actions/setup-node-environment@main
